- name: "Upgrade"
  become: true
  apt:
    upgrade: "yes"

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install dependencies"
  become: true
  apt:
    name: [ "nodejs", "npm" ]
    state: latest
    update_cache: yes