- name: "Copy"
  become: yes
  user: root
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Install dependencies"
  become: true
  user: root
  shell: |
    sudo apt-get -y install npm
    npm install pm2@latest -g

- name: "Extract backend files"
  become: true
  user: root
  shell: |
    cd /home/ubuntu
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz

- name: npm install
  become: true
  user: root
  shell: |
    cd /home/ubuntu
    npm install

- name: "Start"
  user: root
  shell: |
    cd /home/ubuntu/
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls