- name: "Unzip"
  unarchive:
    src: api.tar.gz
    dest: /home/ubuntu/

- name: "Start"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls