- name: "Copy"
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Extract backend files"
  become: true
  shell: |
    cd /home/ubuntu
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz

- name: "Install npm"
  become: true
  shell: |
    cd /home/ubuntu
    npm install

- name: "Start"
  shell: |
    cd /home/ubuntu/
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls